### ISSUE TITLE
[Suggestion] Flèche haut = message précédent

### ISSUE THREAD

**Issue by air-guillaume** [dvp-io/AnoCheat#2]
Un peu comme à la manière des clients IRC, il serait bien que lorsque l'on appuie sur la flèche du haut, on tombe sur le message précédent. Un peu comme mIRC ou comme tout terminal de commande :).

Much appreciated :D

**Comment by antoine-pous** [comment]
Je le met sur ma todo, étant pris par un autre projet actuellement j'ai pas beaucoup de temps pour dev cette feature :/

**Comment by Antoine-Pous** [comment]
Implémenté dans le version 2.2.0 ;)

**Comment by antoine-pous** [comment]
Corrigé et implémenté dans la version 2.4.0.
