### ISSUE TITLE
Documentation : recharger le chat après installation

### ISSUE THREAD

**Issue by ghost** [dvp-io/AnoCheat#4]
Pour ceux qui installent l'AnoCheat tout en étant connecté au chat, et qui n'ont pas l'habitude des scripts de tampermonkey, il peut être sympatique de préciser dans la documentation qu'un rechargement du chat (et donc une reconnexion) est nécessaire pour finaliser l'ajout de l'AnoCheat au chat.

**Comment by antoine-pous** [comment]
Sera disponible lors de la prochaine mise à jour ;o
