### ISSUE TITLE
Documentation : raccourcis claviers non à jour

### ISSUE THREAD

**Issue by ghost** [dvp-io/AnoCheat#5]
Certains raccourcis ne semblent plus à jour, notamment ceux-ci qui se comportent ainsi :

Touches | Actions
------------ | -------------
CTRL + → | ~~Afficher/Masquer la liste des membres~~ conversation suivante
CTRL + ← |  conversation précédente
CTRL + MAJ + → | Afficher/Masquer la liste des membres

Cette différence de comportement a été observée avec Firefox 50.1.0, sur un Windows 8.1 avec TamperMonkey 4.2.5349 et les scripts AnoCheat 2.4.2 et GeckoScript 2.6.2

**Comment by antoine-pous** [comment]
Effectivement CTRL droite/gauche entre en conflit avec un raccourcis implémenté nativement sur le chat.

**Comment by antoine-pous** [comment]
Corrigé dans la version 2.7.0 du GeckoScript, le raccourcis est maintenant `ALT + →`
