### ISSUE TITLE
Ctrl + → après avoir changé le style graphique opère trop d'actions à la fois

### ISSUE THREAD

**Issue by ghost** [dvp-io/AnoCheat#7]
1. Avoir plusieurs conversations d'ouvertes 
2. Sélectionner un style dans la combobox de style, puis ne pas changer le focus en cliquant ailleurs.
3. faire un __Ctrl + →__ ou un __Ctrl + ←__

Normalement es raccourcis __Ctrl + →__ et __Ctrl + ←__ servent à changer de conversation, cette fonctionnalité devrait être la seule chose à survenir pour plus de confort.

Là, non seulement on change de conversation, mais le style change en même temps du fait du focus, et le panel s'ouvre et se referme.

Comportement observé avec Firefox 50.1.0, sur un Windows 8.1 avec TamperMonkey 4.2.5349 et les scripts AnoCheat 2.4.2 et GeckoScript 2.6.2

**Comment by antoine-pous** [comment]
Effectivement après la sélection d'un thème il faut faire un retour de focus sur la zone de saisie

**Comment by antoine-pous** [comment]
Corrigé dans la version 2.7.0 du GeckoScript
